#!/usr/bin/env python3

import configparser
import os
from os.path import isfile
import shutil


class TomlinksException(Exception):
    pass

def process_tilda(section):
    for k, v in section.items():
        section[k] = v.replace("~", os.path.expanduser("~"))
    return section

def parse(dir):
    config = configparser.ConfigParser(allow_unnamed_section=True)
    config.read(f"{dir}/tomlinks.ini")
    if configparser.UNNAMED_SECTION in config:
        section = config[configparser.UNNAMED_SECTION]
        section = process_tilda(section)
        return section
    else:
        raise TomlinksException(f"there is no unnamed section in {dir}/tomlinks.ini")

def sync(src, dest):
    if os.path.isdir(src):
        shutil.copytree(src, dest)
    elif os.path.isfile(src):
        shutil.copy2(src, dest)
    else:
        print(f"not exist: {src}")

for k, v in parse(".").items():
    sync(k, v)
