#!/usr/bin/env python3

import configparser
import os
import shutil
import sys
from pathlib import Path


class TomlinksException(Exception):
    pass

def process_tilda(section):
    for k, v in section.items():
        section[k] = v.replace("~", os.path.expanduser("~"))
    return section

def parse(path):
    config = configparser.ConfigParser(allow_unnamed_section=True)
    config.optionxform = str
    config.read(f"{path}/tomlinks.ini")
    if configparser.UNNAMED_SECTION in config:
        section = config[configparser.UNNAMED_SECTION]
        section = process_tilda(section)
        return section
    else:
        raise TomlinksException(f"there is no unnamed section in {path}/tomlinks.ini")

def sync(src, dest):
    print(f"{src} -> {dest}")
    if not os.path.exists(src):
        print(f"not exist: {src}")
        return
    if os.path.exists(dest):
        if os.path.isdir(dest):
            shutil.rmtree(dest)
        elif os.path.isfile(dest):
            os.remove(dest)
    destParent = Path(dest).parent.absolute()
    os.makedirs(destParent, exist_ok=True)
    if os.path.isdir(src):
        shutil.copytree(src, dest)
    elif os.path.isfile(src):
        shutil.copy2(src, dest)


def restore(path):
    for k, v in parse(path).items():
        sync(os.path.join(path, k), v)

def collect(path):
    for k, v in parse(path).items():
        sync(v, os.path.join(path, k))

def print_help():
    print("""Usage:
  tomlinks restore <package>...
  tomlinks collect <package>...
  tomlinks --help

Commands:
  restore             Copy package files to their system destinations.
  collect             Copy system files back into the package.

Use --help to show this message.""")


def main(args):
    if not args:
        print_help()
        return

    command = None
    for arg in args:
        if arg in ("--help", "help"):
            print_help()
            return
        if command is None:
            if arg == "restore":
                command = restore
            elif arg == "collect":
                command = collect
        else:
            command(arg)

    if command is None:
        print("command wasn't specified; use --help for usage information")


if __name__ == "__main__":
    main(sys.argv[1:])
